In [1]:
import numpy as np
import pandas as pd

#import viz # curriculum example visualizations

np.random.seed(1349)

In [2]:
#1. How likely is it that you roll doubles when rolling two dice?

In [3]:
possible_outcomes = [1,2,3,4,5,6]
trials = 100_000_000
dice = 2
test = np.random.choice(possible_outcomes, trials*dice ).reshape(trials, dice)

In [5]:
test

array([[3, 2],
       [5, 3],
       [4, 4],
       ...,
       [2, 3],
       [4, 2],
       [6, 2]])

In [6]:
#2 If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [10]:
trials = 1_000_000
cols = 8
head = 1
tails = 0
flips = np.random.choice([head, tails], size=(trials,cols))

In [12]:
num_heads = flips.sum(axis=1)

In [13]:
num_heads

array([3, 5, 4, ..., 4, 5, 4])

In [14]:
prob = (num_heads==3).mean() 

In [15]:
prob

0.218961

In [16]:
#There are approximitely 3 web development 
#cohorts for every 1 data science cohort at Codeup.
#Assuming that Codeup randomly selects an alumni to put on a billboard,
#what are the odds that the two billboards I drive past both have data science students on them?

In [21]:
ds_prob = 1/4
rows = 1_000_000
cols = 2
test = np.random.random((rows, cols))

In [22]:
test

array([[0.73207593, 0.33799126],
       [0.6555624 , 0.46427823],
       [0.53341349, 0.87666062],
       ...,
       [0.6914441 , 0.4315685 ],
       [0.48833112, 0.42305234],
       [0.92532017, 0.21931646]])

In [25]:
((test < ds_prob).sum(axis=1)==2).mean()

0.062623

In [26]:
#Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. 
#If on monday the machine is restocked with 17 poptart packages, 
#how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [28]:
pop_avg = 3
std = 1.5
cols = 5
rows = 1_000_000
consumed_pop_tarts = np.random.normal(pop_avg, std, size = (rows,cols))

In [29]:
consumed_pop_tarts

array([[4.1743009 , 0.51488058, 1.6065216 , 2.64719577, 4.15600796],
       [4.97984396, 3.03048025, 0.0448525 , 2.21723984, 3.59954758],
       [3.26269542, 4.1392994 , 4.36060182, 2.21800232, 0.37200108],
       ...,
       [1.70483008, 3.31539088, 3.19114161, 4.83498351, 1.22981557],
       [0.98645854, 1.52056959, 2.28942456, 2.87543317, 3.33427503],
       [5.10354565, 2.92364164, 2.59972248, 1.62393458, 3.62703442]])

In [32]:
answer = (consumed_pop_tarts.sum(axis=1) <= 16).mean()

In [33]:
answer

0.616688

In [34]:
 #Compare Heights

  #  - Men have an average height of 178 cm and standard deviation of 8cm.
  #  - Women have a mean of 170, sd = 6cm.
  #  - If a man and woman are chosen at random, P(woman taller than man)?

In [37]:
avg_men = 178
std_men = 8
avg_women = 170
std_women  = 6

s_men = np.random.normal(avg_men, std_men, 1_000_000)
s_women = np.random.normal(avg_women, std_women, 1_000_000)

In [38]:
s_men

array([167.11136476, 171.03446893, 169.95782969, ..., 170.17310098,
       175.71700986, 190.53368925])

In [41]:
(s_women > s_men).mean()

0.211727

In [42]:
#When installing anaconda on a student's computer, there's a 1 in 250 chance
  # that the download is corrupted and the installation fails. What are the odds
  # that after having 50 students download anaconda, no one has an installation
  # issue?  100 students?

In [45]:
rows = 1_000_000
cols = 50 #150 #450
fail = 1
sucess  = 0
prob= (1/250)

test = np.random.random((rows, cols))


In [47]:
((test<prob).sum(axis=1)==0).mean()

0.81832

In [48]:
#There's a 70% chance on any given day that there will be at least one food
   #truck at Travis Park. However, you haven't seen a food truck there in 3 days.
   #How unlikely is this?

In [49]:
prob = .70
row = 1_000_000
cols = 3
truck = 1
no_truck =0



In [54]:
test = np.random.random((row, cols))

In [55]:
((test < prob).sum(axis=1)==0).mean()

0.027029

In [56]:
# How likely is it that a food truck will show up sometime this week?

In [59]:
lunch_days = np.random.random((row,cols))
calc = ((lunch_days < truck).sum(axis=1)>0).mean()

In [60]:
calc

1.0

In [61]:
#If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [76]:
outcomes = range(0,365)
trials = 40 #20 #23 #40
sim = 1000000
classrooms = np.random.choice(outcomes, size=(sim, trials))

In [77]:
classrooms

array([[251, 176, 207, ..., 223, 338, 252],
       [170, 329, 102, ..., 162, 147, 256],
       [ 88, 274, 219, ..., 300, 315, 105],
       ...,
       [299, 140, 296, ..., 171,  43, 340],
       [228,  22, 140, ..., 197, 364,  54],
       [271, 315, 157, ...,  95,  46,  41]])

In [78]:
twins = [len(np.unique(classrooms[n])) for n in range(0,sim -1 ) if len(np.unique(classrooms[n])) < trials]

In [79]:
prob = len(twins) / sim

In [80]:
prob

0.891784